flake8
cylc/cylc-uiserver pull request #340
Opened 2022-03-30 14:39 UTC by datamel

Flake 8 Fixes
This is a small change with no associated Issue.

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Does not need tests (why? Flake8).
- [x] No change log entry required (why? invisible to users).
- [x] No documentation update required.
- [x] No dependency changes.

2022-03-30 23:09 UTC, hjoliver requested changes
Wondering why these fixes were suddenly required... 

My bad!

Turns out explicitly adding `ignore=SIM9` to `tox.ini`, merged yesterday, turned off a bunch of rules that `flake8` ignores by default (which seems odd, and is a surprise to me!). 

With this version on the command line:
```console
$ flake8 --version    
4.0.1 (
    flake-mutable: 1.2.0, flake8-broken-line: 0.4.0, flake8-bugbear: 22.1.11, 
    flake8-comprehensions: 3.8.0, flake8-debugger: 4.0.0, flake8_builtins: 1.5.2,
    flake8_simplify: 0.19.2, mccabe: 0.6.1, pycodestyle: 2.8.0, pyflakes: 2.4.0
)
```
The rules ignored by default are:
```console
$ flake8 --help
...
  --ignore errors   Comma-separated list of errors and warnings to ignore (or skip).
                            For example, ``--ignore=E4,E51,W234``. (Default:
                            ['B904', 'B903', 'E123', 'W503', 'E126', 'B901', 'E226',
                            W504', 'E121', 'E24', 'E704', 'B950',  'B902'])
...
```

In cylc-flow we explicitly ignore the binary-operator line break rules:
```ini
; tox.ini
[flake8]
ignore=
    ; module level import not at top of file
    E402,
    ; line break before binary operator
    W503,
    ; line break after binary operator
    W504
    ; "experimental" SIM9xx rules (flake8-simplify)
    SIM9
```

So ... I think your indentation fixes on this branch are good, but the W503/4 changes aren't necessary - although they don't hurt.

Instead, maybe you could make `tox.ini` consistent with cylc-flow, on this branch?

2022-03-31 09:44 UTC, datamel commented
Changes made, I have also reverted the changes from W503 and W504 (I think the code was just as readable before and no point in making unnecessary changes to the code.)

2022-03-31 14:40 UTC, wxtim approved these changes

2022-04-04 03:13 UTC, hjoliver approved these changes

2022-04-04 03:13 UTC, merged