setup: migrate to jupyter server 2
cylc/cylc-uiserver pull request #450
Opened 2023-04-21 14:16 UTC by oliver-sanders

Closes #411

Migrate from Jupyter Server 1-2.

There has been a rejig of the `get_current_user` logic so this should be accompanied by a manual security test of authorisation/authentication for all Cylc endpoints.

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [ ] `CHANGES.md` entry included if this is a change that can affect users
- [ ] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

2023-05-02 19:02 UTC, hjoliver commented
Yes, it's ready for review now, and not a big change. It should be merged pretty soon.

2023-05-03 06:40 UTC, hjoliver reviewed
Looks good at first glance. I haven't tested it yet.

2023-05-03 08:55 UTC, oliver-sanders commented
@mahendrapaipuri, we should be able to get this reviewed soonish, however, this feature is scheduled for release along with Cylc 8.2.0 so won't be released until some other work is completed.

If you want to get going with Jupyter Server 2 and Cylc 8.1, we might be able to provide you with a development branch you could install from to save waiting.

2023-05-03 09:01 UTC, mahendrapaipuri commented
Cheers @oliver-sanders!! Well, we are not in a rush. I will keep track of this PR and once it gets merged I can test using the `master` branch on our platform.

2023-05-03 09:35 UTC, oliver-sanders commented
Great, just be aware you'll need to install cylc-flow from master too.

2023-05-17 15:07 UTC, MetRonnie requested changes

2023-05-17 15:07 UTC, MetRonnie commented on setup.cfg
Also need to update 
https://github.com/cylc/cylc-uiserver/blob/0f4500548b6181df16dbf2779f79cce15b639888/setup.cfg#L36
https://github.com/cylc/cylc-uiserver/blob/0f4500548b6181df16dbf2779f79cce15b639888/setup.cfg#L44

2023-05-17 15:12 UTC, mahendrapaipuri commented on setup.cfg
Probably a relevant comment here. Seems like [cylc-flow](https://github.com/cylc/cylc-flow/blob/f81ebc298f8f9514ad588c12da480815d4b286cd/setup.cfg#L53-L54) supports till Python 3.11 and [cylc-uiserver](https://github.com/cylc/cylc-uiserver/blob/ed7f6899132392f6edb9f9f072bc54db92dcd9a8/setup.cfg#L38) only until Python 3.9. Are these classifiers up to date? I mean it is a quite trivial use case that we use them together, right?

2023-05-17 15:27 UTC, MetRonnie commented on setup.cfg
See #388 for why uiserver support is limited to < 3.10

2023-05-18 09:45 UTC, MetRonnie requested changes
Still need to update to `>=3.8`

Or should it be `>=3.8,<3.10`?
https://github.com/cylc/cylc-uiserver/blob/14467609cc3480d0487e3ea8d4294ce03accbdbd/setup.cfg#L43

2023-05-18 09:59 UTC, oliver-sanders commented
sorry, didn't read properly, done.

2023-05-18 10:20 UTC, MetRonnie approved these changes
LGTM, I've done a basic test of running the UI after pip installing on this branch

2023-06-15 10:13 UTC, wxtim commented
- [x] Look at code
- [x] Have a good play with Cylc Hub
- [ ] Pen test

2023-06-15 12:04 UTC, oliver-sanders commented on setup.cfg
> +    jupyter_server>=2.0
```suggestion
    graphql-ws==0.4.4
    jupyter_server>=2.0
```

2023-06-15 12:04 UTC, oliver-sanders commented on setup.cfg
> -    graphql-ws==0.4.4
Cheers.

2023-06-15 15:04 UTC, MetRonnie approved these changes

2023-07-14 15:21 UTC, oliver-sanders commented
Ok, this is now looking ok.

This PR now upgrades us, both to Jupyter Server v2 and to newer versions of Jupyter Hub which has required some re-working of the authorisation which will need to be carefully examined and tested.

The good news is that recent Jupyter Hub versions have added a scope to authorise the starting of other users servers so this improves multi-user functionality greatly.

Along with the [documentation PR](https://github.com/cylc/cylc-doc/pull/625):

* Partially addresses #298
* Closes #275

TODO:

* [ ] Fix tests.
* [ ] Check jupyter_server version range (we may need to up the minimum).
* [ ] Decide the jupyter_hub version range.
* [ ] Further penetration testing of Cylc UIServer and Jupyter Lab according to the [documented configurations](https://github.com/cylc/cylc-doc/pull/625).
* [ ] Add details in the [changes](https://cylc.github.io/cylc-doc/stable/html/reference/changes.html) section of the docs

2023-07-19 10:22 UTC, MetRonnie reviewed
Done another review. No comments at the moment, pending changes

2023-08-21 23:31 UTC, hjoliver approved these changes
LGTM, tested as working.

2023-08-21 23:31 UTC, merged