Avoid requiring `jupyter_config.py` in to be in `uiserver` subdirectory
cylc/cylc-uiserver pull request #594
Opened 2024-05-09 09:14 UTC by wxtim

Previously it was assumed to be in `CYLC_SITE_CONF_PATH/uiserver`.

Ensure that user is warned if file at `CYLC_SITE_CONF_PATH` is
* Unreadable
* Non-existent

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [ ] `CHANGES.md` entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

2024-10-15 09:42 UTC, oliver-sanders requested changes
> Previously it was assumed to be in CYLC_SITE_CONF_PATH/uiserver.

This was correct and consistent with cylc-flow which looks in `$CYLC_SITE_CONF_PATH/flow`.

The `CYLC_SITE_CONF_PATH` directory is supposed to look like this:

```
.
|-- flow
|   `-- global.cylc
`-- uiserver
    `-- jupyter_config.py
```

The intention is that it can be used to configure all of the Cylc components.

2024-10-15 15:24 UTC, wxtim commented
> As of the current versions setting CYLC_SITE_CONF_PATH to the root of the above structure works fine for me.

So this can be closed?

2024-10-15 16:01 UTC, oliver-sanders commented
Check the issue.

2024-10-17 08:55 UTC, oliver-sanders commented
Had a read through the issue, I think these are the main points:

1. The config file didn't get picked up in the location the docs suggested.
  * Check the current behaviour (i.e. `$CYLC_SITE_CONF_DIR/uiserver/jupyter_config.py`) makes sense and is consistent with cylc-flow.
  * If so, amend the docs as needed.
2. If the config file is not readable, there is no error.
  * This is likely Jupyter Server behaviour (try reproducing this using `jupyter server`).
  * If this is special Cylc behaviour, **not** Jupyter Server behaviour, then it's a bug.
  * Otherwise, we could consider pushing an upstream change to Jupyter Server.
3. If no config files are found / readable, they would like a warning stating that users have no access.
  * I'm not sure I get this bit.

2024-10-23 10:54 UTC, wxtim commented
> Had a read through the issue, I think these are the main points:

Sorry, so have I, just not been high enough on my todo-list. It _is_ on my radar.

2024-10-24 12:51 UTC, wxtim commented
> The config file didn't get picked up in the location the docs suggested.
> 
>     * Check the current behaviour (i.e. `$CYLC_SITE_CONF_DIR/uiserver/jupyter_config.py`) makes sense and is consistent with cylc-flow.
> 
>     * If so, amend the docs as needed.

This works as documented [here](https://cylc.github.io/cylc-doc/stable/html/reference/config/global.html#envvar-CYLC_SITE_CONF_PATH), although there might be a case for an extra note on the uiserver app docs.

2024-10-24 13:09 UTC, wxtim commented
@oliver-sanders  -  I'm not convinced that this PR is necessary.

2024-11-07 23:45 UTC, hjoliver commented
Can we close this then?

2025-05-08 14:55 UTC, closed without merging